# Generated by Django 6.0.2 on 2026-02-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='source',
            field=models.CharField(default='Manual', max_length=50),
        ),
    ]
