# Generated by Django 6.0.2 on 2026-02-06 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_match_away_cons_match_away_drop_goals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('try', 'Try (5)'), ('con', 'Conversion (2)'), ('pen', 'Penalty (3)'), ('drop', 'Drop Goal (3)')], max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='api.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.player')),
            ],
            options={
                'verbose_name_plural': 'Player Scores',
            },
        ),
    ]
