# Generated by Django 6.0.2 on 2026-02-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_playerscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='outcome',
            field=models.CharField(choices=[('scored', 'Scored'), ('missed', 'Missed')], default='scored', max_length=10),
        ),
    ]
