# Generated by Django 6.0.2 on 2026-02-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_playerscore_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='featured_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_matches', to='api.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
