# Generated by Django 6.0.2 on 2026-02-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_match_featured_player_match_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='featured_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_sheet_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
