# Generated by Django 6.0.2 on 2026-02-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_cons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_drop_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_pens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_cons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_drop_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_pens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Loss'), ('D', 'Draw')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='scoring_type',
            field=models.CharField(choices=[('standard', 'Standard (5/2/3/3)'), ('tries_only', 'Tries Only (1/0/0/0)')], default='standard', max_length=20),
        ),
    ]
